declare
    @users nvarchar(max) = N'[{"UserAttributes":{"Email":"","PasswordHash":"{\"hash\":\"Z9eYFfkBM0GX5aGgutG8cBnqQT7aoBJcbBuxGonHWzM=\", \"version\":\"admin\"}","UserName":"i.marin_SOFT","Claims":[{"ClaimType":"created_at","ClaimValue":"20190204 12:36:32"},{"ClaimType":"is_enabled","ClaimValue":"True"},{"ClaimType":"name","ClaimValue":"Илья Марин SOFT"},{"ClaimType":"phone","ClaimValue":"646"}],"Roles":"[\"Collector\"]"}},{"UserAttributes":{"Email":"","PasswordHash":"{\"hash\":\"YltgntB+fIUD+b+sqRzAv36f4bLEwsaksI4\/LvTtyDU=\", \"version\":\"admin\"}","UserName":"v.grevtsev_SOFT","Claims":[{"ClaimType":"created_at","ClaimValue":"20181002 06:33:13"},{"ClaimType":"is_enabled","ClaimValue":"True"},{"ClaimType":"name","ClaimValue":"Виктор Гревцев SOFT"},{"ClaimType":"phone","ClaimValue":"647"}],"Roles":"[\"Collector\"]"}},{"UserAttributes":{"Email":"","PasswordHash":"{\"hash\":\"S1oSu299ovMhi6X86YiPWn8ZdczI+O6WhBXhqVzuKBA=\", \"version\":\"admin\"}","UserName":"vc.golovanov_SOFT","Claims":[{"ClaimType":"created_at","ClaimValue":"20190204 12:33:24"},{"ClaimType":"is_enabled","ClaimValue":"True"},{"ClaimType":"name","ClaimValue":"Вячеслав Голованов SOFT"},{"ClaimType":"phone","ClaimValue":"487"}],"Roles":"[\"Collector\"]"}},{"UserAttributes":{"Email":"","PasswordHash":"{\"hash\":\"QgtP1f9K5+872rexzr9VR0fxteUfHaYb4hh5qeO1hnk=\", \"version\":\"admin\"}","UserName":"s.feoktistov_SOFT","Claims":[{"ClaimType":"created_at","ClaimValue":"20180904 09:36:56"},{"ClaimType":"is_enabled","ClaimValue":"True"},{"ClaimType":"name","ClaimValue":"Семен Феоктистов SOFT"},{"ClaimType":"phone","ClaimValue":"571"}],"Roles":"[\"Collector\"]"}},{"UserAttributes":{"Email":"","PasswordHash":"{\"hash\":\"R5A0HbrXPgIKNhAyMpqNeS8MsZrLyPCqMG+LgirOw2w=\", \"version\":\"admin\"}","UserName":"r.mamedov_SOFT","Claims":[{"ClaimType":"created_at","ClaimValue":"20190204 12:36:07"},{"ClaimType":"is_enabled","ClaimValue":"True"},{"ClaimType":"name","ClaimValue":"Рустам Мамедов SOFT"},{"ClaimType":"phone","ClaimValue":"477"}],"Roles":"[\"Collector\"]"}},{"UserAttributes":{"Email":"","PasswordHash":"{\"hash\":\"rppkcdv7IrbGoSkqAE3b31QjB7Lf3tTwjo98LyjBX1g=\", \"version\":\"admin\"}","UserName":"v.chenshan_SOFT","Claims":[{"ClaimType":"created_at","ClaimValue":"20180903 13:53:10"},{"ClaimType":"is_enabled","ClaimValue":"True"},{"ClaimType":"name","ClaimValue":"Владимир Чен-Шан SOFT"},{"ClaimType":"phone","ClaimValue":"404"}],"Roles":"[\"Collector\"]"}}]' 
;

select
    json_query(json_query(oj.Value, '$.UserAttributes')) as UserAttributes
from openjson(@users) oj
where oj.value like N'%SOFT%'
for json path
/
