# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Goncharov.AA\PycharmProjects\LimeProject\col.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(863, 461)
        MainWindow.setMinimumSize(QtCore.QSize(689, 0))
        MainWindow.setMaximumSize(QtCore.QSize(890, 16777215))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../Downloads/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(9, 9, 851, 411))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.project_label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.project_label.setFont(font)
        self.project_label.setText("")
        self.project_label.setAlignment(QtCore.Qt.AlignCenter)
        self.project_label.setObjectName("project_label")
        self.horizontalLayout_3.addWidget(self.project_label)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.all_users_tree = QtWidgets.QTreeWidget(self.widget)
        self.all_users_tree.setMinimumSize(QtCore.QSize(260, 212))
        self.all_users_tree.setMaximumSize(QtCore.QSize(420, 16777215))
        self.all_users_tree.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.all_users_tree.setColumnCount(2)
        self.all_users_tree.setObjectName("all_users_tree")
        self.all_users_tree.header().setCascadingSectionResizes(True)
        self.gridLayout.addWidget(self.all_users_tree, 1, 0, 1, 1)
        self.collectors_tree = QtWidgets.QTreeWidget(self.widget)
        self.collectors_tree.setMinimumSize(QtCore.QSize(311, 212))
        self.collectors_tree.setMaximumSize(QtCore.QSize(420, 16777215))
        self.collectors_tree.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.collectors_tree.setHeaderHidden(False)
        self.collectors_tree.setObjectName("collectors_tree")
        self.collectors_tree.header().setVisible(True)
        self.collectors_tree.header().setCascadingSectionResizes(True)
        self.gridLayout.addWidget(self.collectors_tree, 1, 1, 1, 1)
        self.search_user = QtWidgets.QTextEdit(self.widget)
        self.search_user.setMaximumSize(QtCore.QSize(420, 25))
        self.search_user.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.search_user.setObjectName("search_user")
        self.gridLayout.addWidget(self.search_user, 0, 0, 1, 1)
        self.search_collector = QtWidgets.QTextEdit(self.widget)
        self.search_collector.setMaximumSize(QtCore.QSize(420, 25))
        self.search_collector.setObjectName("search_collector")
        self.gridLayout.addWidget(self.search_collector, 0, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.token_btn = QtWidgets.QPushButton(self.widget)
        self.token_btn.setObjectName("token_btn")
        self.horizontalLayout.addWidget(self.token_btn)
        self.redistribute_btn = QtWidgets.QPushButton(self.widget)
        self.redistribute_btn.setObjectName("redistribute_btn")
        self.horizontalLayout.addWidget(self.redistribute_btn)
        self.new_portfolio_btn = QtWidgets.QPushButton(self.widget)
        self.new_portfolio_btn.setObjectName("new_portfolio_btn")
        self.horizontalLayout.addWidget(self.new_portfolio_btn)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 863, 21))
        self.menuBar.setObjectName("menuBar")
        self.menu = QtWidgets.QMenu(self.menuBar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menuBar)
        self.actionReconnect = QtWidgets.QAction(MainWindow)
        self.actionReconnect.setObjectName("actionReconnect")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionProjects = QtWidgets.QAction(MainWindow)
        self.actionProjects.setObjectName("actionProjects")
        self.menuBar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Collection tool"))
        self.all_users_tree.setSortingEnabled(True)
        self.all_users_tree.headerItem().setText(0, _translate("MainWindow", "Имя"))
        self.all_users_tree.headerItem().setText(1, _translate("MainWindow", "Логин"))
        self.collectors_tree.setSortingEnabled(True)
        self.collectors_tree.headerItem().setText(0, _translate("MainWindow", "Id"))
        self.collectors_tree.headerItem().setText(1, _translate("MainWindow", "Имя"))
        self.collectors_tree.headerItem().setText(2, _translate("MainWindow", "Портфель"))
        self.token_btn.setText(_translate("MainWindow", "Токен"))
        self.redistribute_btn.setText(_translate("MainWindow", "RedistributionOverdueProducts"))
        self.new_portfolio_btn.setText(_translate("MainWindow", "AddProductsToNewCollector"))
        self.menu.setTitle(_translate("MainWindow", "Файл"))
        self.actionReconnect.setText(_translate("MainWindow", "Reconnect"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionProjects.setText(_translate("MainWindow", "Projects"))


