# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'command_tool/command_tool.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(927, 596)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 2, 0, 1, 1)
        self.project_label = QtWidgets.QLabel(self.centralwidget)
        self.project_label.setMinimumSize(QtCore.QSize(0, 29))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.project_label.setFont(font)
        self.project_label.setText("")
        self.project_label.setTextFormat(QtCore.Qt.AutoText)
        self.project_label.setAlignment(QtCore.Qt.AlignCenter)
        self.project_label.setObjectName("project_label")
        self.gridLayout_2.addWidget(self.project_label, 0, 0, 2, 2)
        self.cur_com_tbl = QtWidgets.QTableWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.cur_com_tbl.setFont(font)
        self.cur_com_tbl.setObjectName("cur_com_tbl")
        self.cur_com_tbl.setColumnCount(0)
        self.cur_com_tbl.setRowCount(0)
        self.gridLayout_2.addWidget(self.cur_com_tbl, 5, 0, 1, 1)
        self.src_lay = QtWidgets.QVBoxLayout()
        self.src_lay.setContentsMargins(-1, -1, -1, 0)
        self.src_lay.setSpacing(3)
        self.src_lay.setObjectName("src_lay")
        self.productid_edit = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.productid_edit.sizePolicy().hasHeightForWidth())
        self.productid_edit.setSizePolicy(sizePolicy)
        self.productid_edit.setMaximumSize(QtCore.QSize(106, 16777215))
        self.productid_edit.setObjectName("productid_edit")
        self.src_lay.addWidget(self.productid_edit)
        self.gen_com_bth = QtWidgets.QPushButton(self.centralwidget)
        self.gen_com_bth.setObjectName("gen_com_bth")
        self.src_lay.addWidget(self.gen_com_bth)
        self.add_com_btn = QtWidgets.QPushButton(self.centralwidget)
        self.add_com_btn.setMinimumSize(QtCore.QSize(0, 34))
        self.add_com_btn.setObjectName("add_com_btn")
        self.src_lay.addWidget(self.add_com_btn)
        self.write_com_btn = QtWidgets.QPushButton(self.centralwidget)
        self.write_com_btn.setMinimumSize(QtCore.QSize(0, 34))
        self.write_com_btn.setObjectName("write_com_btn")
        self.src_lay.addWidget(self.write_com_btn)
        self.gridLayout_2.addLayout(self.src_lay, 3, 1, 1, 1)
        self.dst_lay = QtWidgets.QVBoxLayout()
        self.dst_lay.setObjectName("dst_lay")
        self.get_cur_com_btn = QtWidgets.QPushButton(self.centralwidget)
        self.get_cur_com_btn.setObjectName("get_cur_com_btn")
        self.dst_lay.addWidget(self.get_cur_com_btn)
        self.save_cur_com_btn = QtWidgets.QPushButton(self.centralwidget)
        self.save_cur_com_btn.setObjectName("save_cur_com_btn")
        self.dst_lay.addWidget(self.save_cur_com_btn)
        self.del_cur_com_btn = QtWidgets.QPushButton(self.centralwidget)
        self.del_cur_com_btn.setObjectName("del_cur_com_btn")
        self.dst_lay.addWidget(self.del_cur_com_btn)
        self.gridLayout_2.addLayout(self.dst_lay, 5, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 4, 0, 1, 1)
        self.gen_com_tbl = QtWidgets.QTableWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.gen_com_tbl.setFont(font)
        self.gen_com_tbl.setColumnCount(0)
        self.gen_com_tbl.setObjectName("gen_com_tbl")
        self.gen_com_tbl.setRowCount(0)
        self.gridLayout_2.addWidget(self.gen_com_tbl, 3, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 927, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Command tool"))
        self.label.setText(_translate("MainWindow", "Сгенерированные команды"))
        self.gen_com_bth.setText(_translate("MainWindow", "Сгенерировать\n"
"команды"))
        self.add_com_btn.setText(_translate("MainWindow", "Добавить команды\n"
"вручную"))
        self.write_com_btn.setText(_translate("MainWindow", "Записать команды"))
        self.get_cur_com_btn.setText(_translate("MainWindow", "Получить текущие\n"
"команды"))
        self.save_cur_com_btn.setText(_translate("MainWindow", "Сохранить\n"
"изменения"))
        self.del_cur_com_btn.setText(_translate("MainWindow", "Удалить\n"
"выбранные команды"))
        self.label_2.setText(_translate("MainWindow", "Существующие команды"))
        self.menu.setTitle(_translate("MainWindow", "Файл"))


