update t set PercentperDay = 1.69 from prd.shorttermtariff t where sortorder = '1.01'
update t set PercentperDay = 1.69 from prd.shorttermtariff t where sortorder = '1.02'
update t set PercentperDay = 1.69 from prd.shorttermtariff t where sortorder = '1.03'
update t set PercentperDay = 1.69 from prd.shorttermtariff t where sortorder = '1.04'
update t set PercentperDay = 1.69 from prd.shorttermtariff t where sortorder = '2.01'
update t set PercentperDay = 1.69 from prd.shorttermtariff t where sortorder = '2.02'
update t set PercentperDay = 1.69 from prd.shorttermtariff t where sortorder = '2.03'
update t set PercentperDay = 1.68 from prd.shorttermtariff t where sortorder = '2.04'
update t set PercentperDay = 1.68 from prd.shorttermtariff t where sortorder = '3.01'
update t set PercentperDay = 1.67 from prd.shorttermtariff t where sortorder = '3.02'
update t set PercentperDay = 1.67 from prd.shorttermtariff t where sortorder = '3.03'
update t set PercentperDay = 1.67 from prd.shorttermtariff t where sortorder = '3.04'
update t set PercentperDay = 1.69 from prd.longtermtariff t where sortorder = '1.01'
update t set PercentperDay = 1.69 from prd.longtermtariff t where sortorder = '1.02'
update t set PercentperDay = 1.69 from prd.longtermtariff t where sortorder = '1.03'
update t set PercentperDay = 1.69 from prd.longtermtariff t where sortorder = '1.04'
update t set PercentperDay = 0.86 from prd.longtermtariff t where sortorder = '1.05'
update t set PercentperDay = 0.86 from prd.longtermtariff t where sortorder = '1.06'
update t set PercentperDay = 0.86 from prd.longtermtariff t where sortorder = '1.07'
update t set PercentperDay = 0.86 from prd.longtermtariff t where sortorder = '1.08'


begin tran
update prd.shorttermtariff set PercentPerDay = 2.17, MaxAmount = 2000 where SortOrder = '1.01'
update prd.shorttermtariff set PercentPerDay = 2.17, MaxAmount = 2500 where SortOrder = '1.02'
update prd.shorttermtariff set PercentPerDay = 2.17, MaxAmount = 4000 where SortOrder = '1.03'
update prd.shorttermtariff set PercentPerDay = 2.17, MaxAmount = 5000 where SortOrder = '1.04'
update prd.shorttermtariff set PercentPerDay = 2.17, MaxAmount = 6000 where SortOrder = '2.01'
update prd.shorttermtariff set PercentPerDay = 2.17, MaxAmount = 7500 where SortOrder = '2.02'
update prd.shorttermtariff set PercentPerDay = 2.17, MaxAmount = 8500 where SortOrder = '2.03'
update prd.shorttermtariff set PercentPerDay = 2.16, MaxAmount = 9000 where SortOrder = '2.04'
update prd.shorttermtariff set PercentPerDay = 2.15, MaxAmount = 9000 where SortOrder = '3.01'
update prd.shorttermtariff set PercentPerDay = 2.14, MaxAmount = 10000 where SortOrder = '3.02'
update prd.shorttermtariff set PercentPerDay = 2.14, MaxAmount = 11000 where SortOrder = '3.03'
update prd.shorttermtariff set PercentPerDay = 2.14, MaxAmount = 12000 where SortOrder = '3.04'
update prd.longtermtariff set PercentPerDay = 2.17, MaxAmount = 10000 where SortOrder = '1.01'
update prd.longtermtariff set PercentPerDay = 2.17, MaxAmount = 12000 where SortOrder = '1.02'
update prd.longtermtariff set PercentPerDay = 2.17, MaxAmount = 14000 where SortOrder = '1.03'
update prd.longtermtariff set PercentPerDay = 2.17, MaxAmount = 15000 where SortOrder = '1.04'
update prd.longtermtariff set PercentPerDay = 1.1, MaxAmount = 16000 where SortOrder = '1.05'
update prd.longtermtariff set PercentPerDay = 1.1, MaxAmount = 20000 where SortOrder = '1.06'
update prd.longtermtariff set PercentPerDay = 1.1, MaxAmount = 25000 where SortOrder = '1.07'
update prd.longtermtariff set PercentPerDay = 1.1, MaxAmount = 30000 where SortOrder = '1.08'
update prd.longtermtariff set PercentPerDay = 0.95, MaxAmount = 100000 where SortOrder = '1.09'
commit
